import{S as m,i as c}from"./assets/vendor-acbca2f4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC",f=function(r){const s=r.map(({largeImageURL:t,webformatURL:e,tags:o,likes:a,views:p,comments:u,downloads:A})=>`<li class='gallery-item'>
    <a class='gallery-link' href='${t}'>
      <img class='gallery-image' src='${e}' alt='${o}'/>
    </a>
  <div class='container-app'>
  <p><span>Likes</span> ${a}</p>
  <p><span>Views</span> ${p}</p>
  <p><span>Comments</span> ${u}</p>
  <p><span>Downloads</span> ${A}</p>
  </div>
   </li>`).join(""),n=document.querySelector(".gallery");n.innerHTML=s},g=function(){let r=new m(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});r.on("show.simpleLightbox"),r.refresh()},h=function(){c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})};function d(r){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"42209591-dcd9ad54ecaffcfe9e9b64d04",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(n).then(t=>t.json()).then(t=>{const e=t.hits;e.length===0&&h();const o=document.querySelector(".loader");f(e),g(),o.remove()}).catch(t=>{c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${t}`})})}const i=document.querySelector("form");i.addEventListener("submit",y);function y(r){r.preventDefault();const s=i.elements.search.value;if(s===""){c.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Please,enter what do you want to find!"});return}i.insertAdjacentHTML("afterend",'<span class="loader"></span>');const n=document.querySelector(".gallery");n.innerHTML="",d(s),i.reset()}
//# sourceMappingURL=commonHelpers.js.map
