import{S as A,i,a as h}from"./assets/vendor-d74cd0e0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAFpSURBVHgBrZQ9UsMwEIXXQoZhcgCobU6RNKlygPTOKUhPDz00UOBbpE9OgX0FD8xQkBAbrYkyirQrK3Fe5bHX79Nqf6JqPG6AUJzN4DLLIETr/B02eU5+kz7z39UK6uIDfBLpnYqdtc8URLLmiwX8PD1CkO7nLET2NlfSsRRE9jXvgshzmPsg0mcu0lQVufCa2jE2ROhuccyTFK6fX1R2fKvi4TBGJImTCXoiROALqhXrsmhTxCAKojPfqBmoy9L9f+dJzoEWDpCZri6cab5mBkzLC6AgAFGweRCAgoSaowQEqmGeuxSUgXnn/1fE756jAVxBQyHyFHOuu1gADpUtfOfrFhOyXS6dWcA1joq+X9+a+IyrAnWl1recTNrDXcy/Ph8iVbh4OgVxcwtbNeJaTVVBl+wY0xwzl2a6eiWculFtc9S+yH0hlPkBoA+EM3cADmQwaLeqT9gtcjhku42cgwPIaARd8u2mP6EkDQvp61kkAAAAAElFTkSuQmCC",y=function(o){const t=o.map(({largeImageURL:s,webformatURL:e,tags:r,likes:n,views:u,comments:g,downloads:f})=>`<li class='gallery-item'>
    <a class='gallery-link' href='${s}'>
      <img class='gallery-image' src='${e}' alt='${r}'/>
    </a>
  <div class='container-app'>
  <p><span>Likes</span> ${n}</p>
  <p><span>Views</span> ${u}</p>
  <p><span>Comments</span> ${g}</p>
  <p><span>Downloads</span> ${f}</p>
  </div>
   </li>`).join(""),a=document.querySelector(".gallery");a.innerHTML+=t},L=function(){let o=new A(".gallery a",{captionsData:"alt",captionsPosition:"bottom",captionDelay:250});o.on("show.simpleLightbox"),o.refresh()},S=function(){i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})};async function w(o,t){try{const s=new URLSearchParams({key:"42209591-dcd9ad54ecaffcfe9e9b64d04",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:"false",per_page:200,page:t});F();const e=await h.get(`https://pixabay.com/api/?${s}`),r=e.data.hits,n=e.data.totalHits,u=Math.ceil(n/200);return r.length===0&&S(),y(r),P(),L(),u}catch(s){i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:`${s}`})}}const F=function(){const o=document.querySelector(".load"),t=document.querySelector(".loaderMore");o.classList.add("hidden"),t.innerHTML='<span class="loader"></span>'},P=function(){const o=document.querySelector(".load"),t=document.querySelector(".loaderMore");o.classList.remove("hidden"),t.innerHTML=""},p=document.querySelector("form"),E=document.querySelector(".load");document.querySelector(".loaderMore");p.addEventListener("submit",b);E.addEventListener("click",q);let c=1,d;function b(o){c=1,d=p.elements.search.value;const t=document.querySelector(".gallery");t.innerHTML="",m(o)}async function q(o){c+=1;const t=await m(o);c>=t&&i.error({messageColor:"#FFF",color:"blue",iconUrl:l,position:"topRight",message:"We're sorry, but you've reached the end of search results."})}async function m(o){if(o.preventDefault(),d===""){i.error({messageColor:"#FFF",color:"#EF4040",iconUrl:l,position:"topRight",message:"Please,enter what do you want to find!"});return}const t=await w(d,c);return p.reset(),t}
//# sourceMappingURL=commonHelpers.js.map
